### ISSUE TITLE
BSS.Parameters.parameterise error

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace_examples#3]
Execution of ~/sire.app/bin/python test-complex.py (commit 49) fails at the following line of code

ligand = BSS.Parameters.parameterise(ligand, "gaff2").getMolecule()

with the error message

Traceback (most recent call last):
  File "test-complex.py", line 4, in <module>
    ligand = BSS.Parameters.parameterise(ligand, "gaff2").getMolecule()
  File "/home/julien/sire.app/lib/python3.5/site-packages/BioSimSpace-2018.1.1+356.g6df892d.dirty-py3.5.egg/BioSimSpace/Parameters/_process.py", line 181, in getMolecule
AttributeError: 'Process' object has no attribute '_zipname'

**Comment by lohedges** [comment]
This is fixed in the latest commit of the `feature-align` branch. Let me know if you still have problems.
